/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Mhag */

#ifndef _Included_Mhag
#define _Included_Mhag
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Mhag
 * Method:    mhagInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Mhag_mhagInit
  (JNIEnv *, jobject);

/*
 * Class:     Mhag
 * Method:    mhagProc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Mhag_mhagProc
  (JNIEnv *, jobject);

/*
 * Class:     Mhag
 * Method:    genMenuList
 * Signature: (ZZ[I[[Ljava/lang/String;[[I)V
 */
JNIEXPORT void JNICALL Java_Mhag_genMenuList
  (JNIEnv *, jobject, jboolean, jboolean, jintArray, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
