/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Mhag */

#ifndef _Included_Mhag
#define _Included_Mhag
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Mhag
 * Method:    mhagInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Mhag_mhagInit
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_Mhag_mhagProc
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
