
import java.io.FileNotFoundException;
import java.io.PrintStream;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextArea;

/**
 * @program MHAG
 * @ mhagGUI, partially generated by NetBeans IDE
 * @version 1.0
 * @author Tifa@mh3
 */

public class MhagGui extends javax.swing.JFrame {

    /** Creates new form MhagGui */
    public MhagGui() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                rankGroup = new javax.swing.ButtonGroup();
                hunterTypeGroup = new javax.swing.ButtonGroup();
                sexGroup = new javax.swing.ButtonGroup();
                outputGroup = new javax.swing.ButtonGroup();
                jTabbedPane1 = new javax.swing.JTabbedPane();
                calculator = new javax.swing.JPanel();
                rank = new javax.swing.JPanel();
                lowRank = new javax.swing.JRadioButton();
                highRank = new javax.swing.JRadioButton();
                hunterType = new javax.swing.JPanel();
                blade = new javax.swing.JRadioButton();
                gunner = new javax.swing.JRadioButton();
                sex = new javax.swing.JPanel();
                male = new javax.swing.JRadioButton();
                female = new javax.swing.JRadioButton();
                setup = new javax.swing.JPanel();
                weaponMenu = new javax.swing.JComboBox();
                headMenu = new javax.swing.JComboBox();
                chestMenu = new javax.swing.JComboBox();
                armsMenu = new javax.swing.JComboBox();
                waistMenu = new javax.swing.JComboBox();
                legsMenu = new javax.swing.JComboBox();
                charmMenu = new javax.swing.JComboBox();
                weaponLabel = new javax.swing.JLabel();
                headLabel = new javax.swing.JLabel();
                chestLabel = new javax.swing.JLabel();
                armsLabel = new javax.swing.JLabel();
                waistLabel = new javax.swing.JLabel();
                legsLabel = new javax.swing.JLabel();
                charmLabel = new javax.swing.JLabel();
                charmSkillLabel = new javax.swing.JLabel();
                weaponSlot1 = new javax.swing.JComboBox();
                weaponSlot2 = new javax.swing.JComboBox();
                weaponSlot3 = new javax.swing.JComboBox();
                headSlot1 = new javax.swing.JComboBox();
                headSlot2 = new javax.swing.JComboBox();
                headSlot3 = new javax.swing.JComboBox();
                chestSlot1 = new javax.swing.JComboBox();
                chestSlot2 = new javax.swing.JComboBox();
                chestSlot3 = new javax.swing.JComboBox();
                armSlot1 = new javax.swing.JComboBox();
                armSlot2 = new javax.swing.JComboBox();
                armSlot3 = new javax.swing.JComboBox();
                waistSlot1 = new javax.swing.JComboBox();
                waistSlot2 = new javax.swing.JComboBox();
                waistSlot3 = new javax.swing.JComboBox();
                legSlot1 = new javax.swing.JComboBox();
                legSlot2 = new javax.swing.JComboBox();
                legSlot3 = new javax.swing.JComboBox();
                charmSlot1 = new javax.swing.JComboBox();
                charmSlot2 = new javax.swing.JComboBox();
                charmSlot3 = new javax.swing.JComboBox();
                charmSkill1 = new javax.swing.JComboBox();
                charmSkill2 = new javax.swing.JComboBox();
                skillPoint1 = new javax.swing.JLabel();
                skillPoint2 = new javax.swing.JLabel();
                output = new javax.swing.JPanel();
                text = new javax.swing.JRadioButton();
                html = new javax.swing.JRadioButton();
                code = new javax.swing.JRadioButton();
                saveOutput = new javax.swing.JButton();
                jTextData = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                jScrollPreview = new javax.swing.JScrollPane();
                jTextPreview = new javax.swing.JTextArea();
                setNamePanel = new javax.swing.JPanel();
                jTextSetName = new javax.swing.JTextField();
                batch = new javax.swing.JPanel();
                generator = new javax.swing.JPanel();
                about = new javax.swing.JPanel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setResizable(false);

                jTabbedPane1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N

                rank.setBorder(javax.swing.BorderFactory.createTitledBorder("Rank"));

                rankGroup.add(lowRank);
                lowRank.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                lowRank.setText("Low Rank");
                lowRank.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                lowRankActionPerformed(evt);
                        }
                });

                rankGroup.add(highRank);
                highRank.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                highRank.setSelected(true);
                highRank.setText("High Rank");
                highRank.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                highRankActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout rankLayout = new javax.swing.GroupLayout(rank);
                rank.setLayout(rankLayout);
                rankLayout.setHorizontalGroup(
                        rankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(rankLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(rankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lowRank)
                                        .addComponent(highRank))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                rankLayout.setVerticalGroup(
                        rankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(rankLayout.createSequentialGroup()
                                .addComponent(lowRank)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(highRank))
                );

                hunterType.setBorder(javax.swing.BorderFactory.createTitledBorder("Hunter Type"));

                hunterTypeGroup.add(blade);
                blade.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                blade.setSelected(true);
                blade.setText("Blademaster");
                blade.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bladeActionPerformed(evt);
                        }
                });

                hunterTypeGroup.add(gunner);
                gunner.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                gunner.setText("Gunner");
                gunner.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                gunnerActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout hunterTypeLayout = new javax.swing.GroupLayout(hunterType);
                hunterType.setLayout(hunterTypeLayout);
                hunterTypeLayout.setHorizontalGroup(
                        hunterTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(hunterTypeLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(blade))
                        .addGroup(hunterTypeLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(gunner)
                                .addContainerGap(35, Short.MAX_VALUE))
                );
                hunterTypeLayout.setVerticalGroup(
                        hunterTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(hunterTypeLayout.createSequentialGroup()
                                .addComponent(blade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gunner))
                );

                sex.setBorder(javax.swing.BorderFactory.createTitledBorder("Gender"));

                sexGroup.add(male);
                male.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                male.setSelected(true);
                male.setText("Male");
                male.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                maleActionPerformed(evt);
                        }
                });

                sexGroup.add(female);
                female.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                female.setText("Female");
                female.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                femaleActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout sexLayout = new javax.swing.GroupLayout(sex);
                sex.setLayout(sexLayout);
                sexLayout.setHorizontalGroup(
                        sexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sexLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(sexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(male)
                                        .addComponent(female))
                                .addContainerGap(30, Short.MAX_VALUE))
                );
                sexLayout.setVerticalGroup(
                        sexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sexLayout.createSequentialGroup()
                                .addComponent(male)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(female))
                );

                setup.setBorder(javax.swing.BorderFactory.createTitledBorder("Setup"));
                setup.setPreferredSize(new java.awt.Dimension(625, 390));

                weaponMenu.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                weaponMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Slot", "1 Slot", "2 Slots", "3 Slots" }));
                weaponMenu.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                weaponMenuActionPerformed(evt);
                        }
                });

                headMenu.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                headMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                headMenu.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                headMenuActionPerformed(evt);
                        }
                });

                chestMenu.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                chestMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                chestMenu.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                chestMenuActionPerformed(evt);
                        }
                });

                armsMenu.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                armsMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                armsMenu.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                armsMenuActionPerformed(evt);
                        }
                });

                waistMenu.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                waistMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                waistMenu.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                waistMenuActionPerformed(evt);
                        }
                });

                legsMenu.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                legsMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                legsMenu.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                legsMenuActionPerformed(evt);
                        }
                });

                charmMenu.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                charmMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                charmMenu.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                charmMenuActionPerformed(evt);
                        }
                });

                weaponLabel.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                weaponLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/weapon.png"))); // NOI18N
                weaponLabel.setLabelFor(weaponMenu);
                weaponLabel.setToolTipText("Weapon");

                headLabel.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                headLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/head.png"))); // NOI18N
                headLabel.setLabelFor(headMenu);
                headLabel.setToolTipText("Head");

                chestLabel.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                chestLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/chest.png"))); // NOI18N
                chestLabel.setLabelFor(chestMenu);
                chestLabel.setToolTipText("Chest");

                armsLabel.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                armsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/arms.png"))); // NOI18N
                armsLabel.setLabelFor(armsMenu);
                armsLabel.setToolTipText("Arms");

                waistLabel.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                waistLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/waist.png"))); // NOI18N
                waistLabel.setLabelFor(waistMenu);
                waistLabel.setToolTipText("Waist");

                legsLabel.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                legsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/legs.png"))); // NOI18N
                legsLabel.setLabelFor(legsMenu);
                legsLabel.setToolTipText("Legs");

                charmLabel.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                charmLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/charm.png"))); // NOI18N
                charmLabel.setLabelFor(charmMenu);
                charmLabel.setToolTipText("Charm");

                charmSkillLabel.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                charmSkillLabel.setLabelFor(charmSkill1);
                charmSkillLabel.setText("Charm Skill");

                weaponSlot1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                weaponSlot1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                weaponSlot1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                weaponSlot1ActionPerformed(evt);
                        }
                });

                weaponSlot2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                weaponSlot2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                weaponSlot2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                weaponSlot2ActionPerformed(evt);
                        }
                });

                weaponSlot3.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                weaponSlot3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                weaponSlot3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                weaponSlot3ActionPerformed(evt);
                        }
                });

                headSlot1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                headSlot1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                headSlot1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                headSlot1ActionPerformed(evt);
                        }
                });

                headSlot2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                headSlot2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                headSlot2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                headSlot2ActionPerformed(evt);
                        }
                });

                headSlot3.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                headSlot3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                headSlot3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                headSlot3ActionPerformed(evt);
                        }
                });

                chestSlot1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                chestSlot1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                chestSlot1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                chestSlot1ActionPerformed(evt);
                        }
                });

                chestSlot2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                chestSlot2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                chestSlot2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                chestSlot2ActionPerformed(evt);
                        }
                });

                chestSlot3.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                chestSlot3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                chestSlot3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                chestSlot3ActionPerformed(evt);
                        }
                });

                armSlot1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                armSlot1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                armSlot1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                armSlot1ActionPerformed(evt);
                        }
                });

                armSlot2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                armSlot2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                armSlot2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                armSlot2ActionPerformed(evt);
                        }
                });

                armSlot3.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                armSlot3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                armSlot3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                armSlot3ActionPerformed(evt);
                        }
                });

                waistSlot1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                waistSlot1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                waistSlot1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                waistSlot1ActionPerformed(evt);
                        }
                });

                waistSlot2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                waistSlot2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                waistSlot2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                waistSlot2ActionPerformed(evt);
                        }
                });

                waistSlot3.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                waistSlot3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                waistSlot3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                waistSlot3ActionPerformed(evt);
                        }
                });

                legSlot1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                legSlot1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                legSlot1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                legSlot1ActionPerformed(evt);
                        }
                });

                legSlot2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                legSlot2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                legSlot2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                legSlot2ActionPerformed(evt);
                        }
                });

                legSlot3.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                legSlot3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                legSlot3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                legSlot3ActionPerformed(evt);
                        }
                });

                charmSlot1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                charmSlot1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                charmSlot1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                charmSlot1ActionPerformed(evt);
                        }
                });

                charmSlot2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                charmSlot2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                charmSlot2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                charmSlot2ActionPerformed(evt);
                        }
                });

                charmSlot3.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                charmSlot3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                charmSlot3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                charmSlot3ActionPerformed(evt);
                        }
                });

                charmSkill1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                charmSkill1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                charmSkill1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                charmSkill1ActionPerformed(evt);
                        }
                });

                charmSkill2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                charmSkill2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
                charmSkill2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                charmSkill2ActionPerformed(evt);
                        }
                });

                skillPoint1.setLabelFor(charmSkill1);
                skillPoint1.setText("+10");

                skillPoint2.setLabelFor(charmSkill2);
                skillPoint2.setText("-10");

                javax.swing.GroupLayout setupLayout = new javax.swing.GroupLayout(setup);
                setup.setLayout(setupLayout);
                setupLayout.setHorizontalGroup(
                        setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(setupLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(setupLayout.createSequentialGroup()
                                                .addComponent(weaponLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(setupLayout.createSequentialGroup()
                                                                .addComponent(charmSkillLabel)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(charmSkill1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(skillPoint1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(charmSkill2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(skillPoint2))
                                                        .addGroup(setupLayout.createSequentialGroup()
                                                                .addComponent(weaponMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(weaponSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(weaponSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(weaponSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(setupLayout.createSequentialGroup()
                                                .addComponent(headLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(headMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(headSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(headSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(headSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(setupLayout.createSequentialGroup()
                                                .addComponent(chestLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(chestMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(chestSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(chestSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(chestSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(setupLayout.createSequentialGroup()
                                                .addComponent(armsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(armsMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(armSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(armSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(armSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(setupLayout.createSequentialGroup()
                                                .addComponent(waistLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(waistMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(waistSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(waistSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(waistSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(setupLayout.createSequentialGroup()
                                                .addComponent(legsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(legsMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(legSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(legSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(legSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(setupLayout.createSequentialGroup()
                                                .addComponent(charmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(charmMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(charmSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)
                                                .addComponent(charmSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(charmSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(18, Short.MAX_VALUE))
                );
                setupLayout.setVerticalGroup(
                        setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(setupLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(setupLayout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addComponent(weaponLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(weaponMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(weaponSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(weaponSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(weaponSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(headSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(headSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(headSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(headMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(headLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(chestMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(chestLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(chestSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(chestSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(chestSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(armsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(armSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(armSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(armsMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(armSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(waistMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(waistSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(waistSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(waistSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(waistLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(legsMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(legSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(legSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(legSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(legsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(charmMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(charmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(charmSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(charmSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(charmSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(charmSkillLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(charmSkill1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(skillPoint1)
                                        .addComponent(charmSkill2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(skillPoint2))
                                .addContainerGap(25, Short.MAX_VALUE))
                );

                output.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));

                outputGroup.add(text);
                text.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                text.setSelected(true);
                text.setText("TEXT");
                text.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                textActionPerformed(evt);
                        }
                });

                outputGroup.add(html);
                html.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                html.setText("HTML");
                html.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                htmlActionPerformed(evt);
                        }
                });

                outputGroup.add(code);
                code.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                code.setText("Code");
                code.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                codeActionPerformed(evt);
                        }
                });

                saveOutput.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
                saveOutput.setText("Save");
                saveOutput.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                saveOutputActionPerformed(evt);
                        }
                });

                jTextData.setText("MyData");
                jTextData.setToolTipText("input your save data ");

                jLabel1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                jLabel1.setText("Data File");

                javax.swing.GroupLayout outputLayout = new javax.swing.GroupLayout(output);
                output.setLayout(outputLayout);
                outputLayout.setHorizontalGroup(
                        outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(outputLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(text)
                                .addGap(18, 18, 18)
                                .addComponent(html)
                                .addGap(18, 18, 18)
                                .addComponent(code)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29)
                                .addComponent(jTextData, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saveOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                .addContainerGap())
                );
                outputLayout.setVerticalGroup(
                        outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outputLayout.createSequentialGroup()
                                .addGroup(outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(text)
                                        .addComponent(html)
                                        .addComponent(code)
                                        .addComponent(saveOutput)
                                        .addComponent(jTextData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addGap(117, 117, 117))
                );

                jScrollPreview.setHorizontalScrollBar(null);

                jTextPreview.setColumns(20);
                jTextPreview.setEditable(false);
                jTextPreview.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                jTextPreview.setForeground(new java.awt.Color(1, 1, 1));
                jTextPreview.setRows(5);
                jTextPreview.setText("================================================================================\n Medic's Set                             High Rank   Blademaster \n--------------------------------------------------------------------------------\n Weapon                                  OO-   Steadfast+ Recovery \n Grace Earring                           ---     \n Gobul Mail+                             O--   Steadfast+  \n Gobul Vambraces+                        O--   Medicine  \n Gobul Faulds+                           O--   Medicine  \n Gobul Greaves+                          OOO   Voracious  \n Rec Level +7                            OO-   Panacea  \n--------------------------------------------------------------------------------\n                     WEP HEA CHE ARM WAI LEG CHA TOT\n Max Defense         ---  10  74  74  74  74 --- 306 \n Resist: Fire        ---   0  -2  -2  -2  -2 ---  -8 \n         Water       ---   0   4   4   4   4 ---  16 \n         Ice         ---   0   0   0   0   0 ---   0 \n         Thunder     ---   0  -4  -4  -4  -4 --- -16 \n         Dragon      ---   0   2   2   2   2 ---   8 \n--------------------------------------------------------------------------------\n SKills: Wide-Range  ---  20 --- --- --- --- ---  20 → Wide-Range +2\n         Stun          2 ---   4   4   4   2 ---  16 → Negate Stun\n         Eating       -1 ---   2   4   5   5 ---  15 → Speed Eating +2\n         Rec Level   --- --- ---   1   1  -2  10  10 → Recovery Up\n         Expert      --- ---   3   2   1   2 ---   8   ---\n         Rec Speed     1 ---  -2  -2  -2  -2  -1  -8   ---\n================================================================================");
                jTextPreview.setBorder(javax.swing.BorderFactory.createTitledBorder("Preview"));
                jTextPreview.setOpaque(false);
                jScrollPreview.setViewportView(jTextPreview);

                setNamePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Set Name"));

                jTextSetName.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                jTextSetName.setText("Unnamed Set");
                jTextSetName.setToolTipText("input your save data ");

                javax.swing.GroupLayout setNamePanelLayout = new javax.swing.GroupLayout(setNamePanel);
                setNamePanel.setLayout(setNamePanelLayout);
                setNamePanelLayout.setHorizontalGroup(
                        setNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setNamePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextSetName, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                .addContainerGap())
                );
                setNamePanelLayout.setVerticalGroup(
                        setNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(setNamePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextSetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout calculatorLayout = new javax.swing.GroupLayout(calculator);
                calculator.setLayout(calculatorLayout);
                calculatorLayout.setHorizontalGroup(
                        calculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(calculatorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(calculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(output, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(calculatorLayout.createSequentialGroup()
                                                .addComponent(rank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(hunterType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(setNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(setup, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                calculatorLayout.setVerticalGroup(
                        calculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(calculatorLayout.createSequentialGroup()
                                .addGroup(calculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPreview, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, calculatorLayout.createSequentialGroup()
                                                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(calculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(setNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(calculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(sex, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(hunterType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(rank, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(setup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                jTabbedPane1.addTab("Calculator", calculator);

                javax.swing.GroupLayout batchLayout = new javax.swing.GroupLayout(batch);
                batch.setLayout(batchLayout);
                batchLayout.setHorizontalGroup(
                        batchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1226, Short.MAX_VALUE)
                );
                batchLayout.setVerticalGroup(
                        batchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 535, Short.MAX_VALUE)
                );

                jTabbedPane1.addTab("Batch", batch);

                javax.swing.GroupLayout generatorLayout = new javax.swing.GroupLayout(generator);
                generator.setLayout(generatorLayout);
                generatorLayout.setHorizontalGroup(
                        generatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1226, Short.MAX_VALUE)
                );
                generatorLayout.setVerticalGroup(
                        generatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 535, Short.MAX_VALUE)
                );

                jTabbedPane1.addTab("Generator", generator);

                javax.swing.GroupLayout aboutLayout = new javax.swing.GroupLayout(about);
                about.setLayout(aboutLayout);
                aboutLayout.setHorizontalGroup(
                        aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1226, Short.MAX_VALUE)
                );
                aboutLayout.setVerticalGroup(
                        aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 535, Short.MAX_VALUE)
                );

                jTabbedPane1.addTab("About", about);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1238, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void bladeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bladeActionPerformed
	    // set to blademaster
	    if(set.getBlade() == true )return;

	    set.setBlade(true);
	    initSetup(set.getLowRank(), set.getBlade(), set.getFemale());
    }//GEN-LAST:event_bladeActionPerformed

    private void highRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highRankActionPerformed
	    // set to high Rank
	    if(set.getLowRank() == false )return;

	    set.setLowRank(false);
	    initSetup(set.getLowRank(), set.getBlade(), set.getFemale());
    }//GEN-LAST:event_highRankActionPerformed

    private void lowRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowRankActionPerformed
	    // set to Low Rank
	    if(set.getLowRank() == true )return;

	    set.setLowRank(true);
	    initSetup(set.getLowRank(), set.getBlade(), set.getFemale());
    }//GEN-LAST:event_lowRankActionPerformed

    private void gunnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gunnerActionPerformed
	    // set to blademaster
	    if(set.getBlade() == false )return;

	    set.setBlade(false);
	    initSetup(set.getLowRank(), set.getBlade(), set.getFemale());
    }//GEN-LAST:event_gunnerActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
	    // set to male
	    if(set.getFemale() == false )return;

	    set.setFemale(false);
	    // TODO get & keep armorID

	    changeGender(set.getLowRank(), set.getBlade(), set.getFemale());
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
	    // set to female
	    if(set.getFemale() == true )return;

	    set.setFemale(true);
	    // TODO get & keep armorID

	    changeGender(set.getLowRank(), set.getBlade(), set.getFemale());
    }//GEN-LAST:event_femaleActionPerformed

    private void headMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headMenuActionPerformed
	    armorMenuAction(0);
    }//GEN-LAST:event_headMenuActionPerformed

    private void chestMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chestMenuActionPerformed
	    armorMenuAction(1);
    }//GEN-LAST:event_chestMenuActionPerformed

    private void armsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_armsMenuActionPerformed
	    armorMenuAction(2);
    }//GEN-LAST:event_armsMenuActionPerformed

    private void waistMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waistMenuActionPerformed
	    armorMenuAction(3);
    }//GEN-LAST:event_waistMenuActionPerformed

    private void legsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legsMenuActionPerformed
	    armorMenuAction(4);
    }//GEN-LAST:event_legsMenuActionPerformed

    private void weaponMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weaponMenuActionPerformed

	   int ind = weaponMenu.getSelectedIndex();
	   int bodyPart = 5;

	   if(ind <= 0 )
	   {
		   set.setInUse(bodyPart, false);
		   set.setNumJewel(bodyPart, 0);  //initiate jewel
		   Arrays.fill(jewelInd[bodyPart], 0);  // inititate jewelInd
		   Arrays.fill(jewelMenuType[bodyPart], 0);  // inititate menu type
		   for (int i = 0; i < 3; i++)
		   {
			   changeJewelSlot(bodyPart, i, set.getLowRank(), 0, false);
		   }
		   calSetGUI();
	   }
	   else
	   {
		   set.setInUse(bodyPart, true);

		   // get number of slots
		   int nSlot = ind;
		   //initialiate jewel menu lists
		   set.setNumJewel(bodyPart, nSlot);
		   Arrays.fill(jewelInd[bodyPart], 0);  // inititate jewelInd
		   for (int i = 0; i < nSlot; i++)  //start from 1
		   {
			   changeJewelSlot(bodyPart, i, set.getLowRank(), nSlot, true);
		   }
		   for (int i = nSlot; i < 3; i++)
		   {
			   changeJewelSlot(bodyPart, i, set.getLowRank(), 0, false);
		   }

	   }

    }//GEN-LAST:event_weaponMenuActionPerformed

    private void charmMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charmMenuActionPerformed

	   int ind = charmMenu.getSelectedIndex();
	   int bodyPart = 6;

	   if(ind <= 0 )
	   {
		   set.setInUse(bodyPart, false);
		   set.setNumJewel(bodyPart, 0);  //initiate jewel
		   Arrays.fill(jewelInd[bodyPart], 0);  // inititate jewelInd
		   Arrays.fill(jewelMenuType[bodyPart], 0);  // inititate menu type
		   for (int i = 0; i < 3; i++)   //change charm jewel
			   changeJewelSlot(bodyPart, i, set.getLowRank(), 0, false);
		   for (int i = 0; i < 2; i++)  //change charm skill
			   changeCharmSkill(i, "C", false);
		   skillPoint1.setText("");
		   skillPoint2.setText("");
		   set.setCharmID(-1);
		   set.setNumCharmSkill(0);
	   }
	   else
	   {
		   //obtain list value
		   int[] list = mhagData.getCharmList(set.getLowRank());
		   int charmID = list[ind];
		   if(set.getCharmID() == charmID)return; // no change

		   // set Jewel id
		   set.setInUse(bodyPart, true);
		   set.setCharmID(charmID);

		   // get number of slots
		   Charm charm = mhagData.getCharm(charmID);
		   int nSlot = charm.getNumSlot();
		   //initialiate jewel menu lists
		   set.setNumJewel(bodyPart, nSlot);
		   Arrays.fill(jewelInd[bodyPart], 0);  // inititate jewelInd
		   for (int i = 0; i < 3; i++) //start from 1
		   {
			   if(i < nSlot)
			   {
				   changeJewelSlot(bodyPart, i, set.getLowRank(), nSlot, true);
			   }
			   else
			   {
				   changeJewelSlot(bodyPart, i, set.getLowRank(), 0, false);
			   }
		   }
		   //change charmSkill

		   int nSkill = charm.getNumSkill();
		   set.setNumCharmSkill(nSkill);

		   if(nSkill == 1)
		   {
			   String skillClass = charm.getSkillClass()[0];
			   changeCharmSkill(0, skillClass, true);
			   skillPoint1.setText(String.format(
				   "%+d",charm.getSkillPoint()[0]));
			   changeCharmSkill(1, "C", false);
			   skillPoint2.setText("");

		   }
		   else if(nSkill == 2)
		   {
			   String skillClass = charm.getSkillClass()[0];
			   changeCharmSkill(0, skillClass, true);
			   skillPoint1.setText(String.format(
				   "%+d",charm.getSkillPoint()[0]));
			   skillClass = charm.getSkillClass()[1];
			   changeCharmSkill(1, skillClass, true);
			   skillPoint2.setText(String.format(
				   "%+d",charm.getSkillPoint()[1]));
		   }
		   else
		   {
			   changeCharmSkill(0, "C", false);
			   skillPoint1.setText("");
			   changeCharmSkill(1, "C", false);
			   skillPoint2.setText("");
		   }

	   }
	   calSetGUI();
    }//GEN-LAST:event_charmMenuActionPerformed

    private void charmSkill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charmSkill1ActionPerformed
	    //charm skill 1
	   int ind = charmSkill1.getSelectedIndex();
	   if(ind < 0) return;

	   Charm charm = mhagData.getCharm(set.getCharmID());
	   int[] list = mhagData.getSkillList(charm.getSkillClass()[0]);

	   set.setCharmSkillID(0,list[ind]);
	   set.setNumCharmSkill(charm.getNumSkill());

	   calSetGUI();

    }//GEN-LAST:event_charmSkill1ActionPerformed

    private void charmSkill2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charmSkill2ActionPerformed
	    //charm skill 2
	   int ind = charmSkill2.getSelectedIndex();
	   if(ind < 0) return;

	   Charm charm = mhagData.getCharm(set.getCharmID());
	   int[] list = mhagData.getSkillList(charm.getSkillClass()[1]);

	   set.setCharmSkillID(1,list[ind]);
	   set.setNumCharmSkill(2);

	   calSetGUI();

    }//GEN-LAST:event_charmSkill2ActionPerformed

    private void weaponSlot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weaponSlot1ActionPerformed
	    jewelSlotAction(5, 0);
    }//GEN-LAST:event_weaponSlot1ActionPerformed

    private void weaponSlot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weaponSlot2ActionPerformed
	    jewelSlotAction(5, 1);
    }//GEN-LAST:event_weaponSlot2ActionPerformed

    private void weaponSlot3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weaponSlot3ActionPerformed
	    jewelSlotAction(5, 2);
    }//GEN-LAST:event_weaponSlot3ActionPerformed

    private void headSlot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headSlot1ActionPerformed
	    jewelSlotAction(0, 0);
    }//GEN-LAST:event_headSlot1ActionPerformed

    private void headSlot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headSlot2ActionPerformed
	    jewelSlotAction(0, 1);
    }//GEN-LAST:event_headSlot2ActionPerformed

    private void headSlot3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headSlot3ActionPerformed
	    jewelSlotAction(0, 2);
    }//GEN-LAST:event_headSlot3ActionPerformed

    private void chestSlot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chestSlot1ActionPerformed
	    jewelSlotAction(1, 0);
    }//GEN-LAST:event_chestSlot1ActionPerformed

    private void chestSlot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chestSlot2ActionPerformed
	    jewelSlotAction(1, 1);
    }//GEN-LAST:event_chestSlot2ActionPerformed

    private void chestSlot3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chestSlot3ActionPerformed
	    jewelSlotAction(1, 2);
    }//GEN-LAST:event_chestSlot3ActionPerformed

    private void armSlot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_armSlot1ActionPerformed
	    jewelSlotAction(2, 0);
    }//GEN-LAST:event_armSlot1ActionPerformed

    private void armSlot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_armSlot2ActionPerformed
	    jewelSlotAction(2, 1);
    }//GEN-LAST:event_armSlot2ActionPerformed

    private void armSlot3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_armSlot3ActionPerformed
	    jewelSlotAction(2, 2);
    }//GEN-LAST:event_armSlot3ActionPerformed

    private void waistSlot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waistSlot1ActionPerformed
	    jewelSlotAction(3, 0);
    }//GEN-LAST:event_waistSlot1ActionPerformed

    private void waistSlot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waistSlot2ActionPerformed
	    jewelSlotAction(3, 1);
    }//GEN-LAST:event_waistSlot2ActionPerformed

    private void waistSlot3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waistSlot3ActionPerformed
	    jewelSlotAction(3, 2);
    }//GEN-LAST:event_waistSlot3ActionPerformed

    private void legSlot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legSlot1ActionPerformed
	    jewelSlotAction(4, 0);
    }//GEN-LAST:event_legSlot1ActionPerformed

    private void legSlot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legSlot2ActionPerformed
	    jewelSlotAction(4, 1);
    }//GEN-LAST:event_legSlot2ActionPerformed

    private void legSlot3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legSlot3ActionPerformed
	    jewelSlotAction(4, 2);
    }//GEN-LAST:event_legSlot3ActionPerformed

    private void charmSlot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charmSlot1ActionPerformed
	    jewelSlotAction(6, 0);
    }//GEN-LAST:event_charmSlot1ActionPerformed

    private void charmSlot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charmSlot2ActionPerformed
	    jewelSlotAction(6, 1);
    }//GEN-LAST:event_charmSlot2ActionPerformed

    private void charmSlot3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charmSlot3ActionPerformed
	    jewelSlotAction(6, 2);
    }//GEN-LAST:event_charmSlot3ActionPerformed

    private void textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textActionPerformed
	    saveOpt = 0;
    }//GEN-LAST:event_textActionPerformed

    private void htmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htmlActionPerformed
	    saveOpt = 1;
    }//GEN-LAST:event_htmlActionPerformed

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed
	    saveOpt = 2;
}//GEN-LAST:event_codeActionPerformed

    private void saveOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveOutputActionPerformed
	    try {
		    appendData();
	    } catch (FileNotFoundException ex) {
		    Logger.getLogger(MhagGui.class.getName()).log(Level.SEVERE, null, ex);
	    }
}//GEN-LAST:event_saveOutputActionPerformed

    private void appendData() throws FileNotFoundException
    {
	    calSetGUI();
	    PrintStream saveStream;
	    String saveData = jTextData.getText();
	    if(saveOpt == 0) //text file
	    {
		    if(!saveData.endsWith(".txt"))
			    saveData = saveData + ".txt";
		    saveStream = MhagUtil.streamAppendFile(saveData);
		    mhag.setOutFormat(0);
		    set.save(mhag, mhagData, saveStream);  // save results

	    }
	    else if (saveOpt == 1)
	    {
		    if(!saveData.endsWith(".html"))
			    saveData = saveData + ".html";
		    saveStream = MhagUtil.streamAppendFile(saveData);
		    mhag.setOutFormat(1);

		    saveStream.printf("<p style=\"page-break-before:always\">" +
				"Set :</p>\n");
		    set.save(mhag, mhagData, saveStream);  // save results

		    mhag.setOutFormat(0);

	    }
	    else
	    {
		    if(!saveData.endsWith(".code"))
			    saveData = saveData + ".code";
		    saveStream = MhagUtil.streamAppendFile(saveData);
		    String codeline = set.getSetCode();   //get set code
		    saveStream.println(codeline);
	    }
	    saveStream.close();

    }

    private void armorMenuAction(int bodyPart)
    {
	    if(adjust)return;  //for male/female change

	   JComboBox bodyMenu = getArmorMenuObj(bodyPart);

	   int ind = bodyMenu.getSelectedIndex();

	   if(ind <= 0 )
	   {
		   set.setInUse(bodyPart, false);
		   set.setNumJewel(bodyPart, 0);  //initiate jewel
		   Arrays.fill(jewelInd[bodyPart], 0);  // inititate jewelInd
		   Arrays.fill(jewelMenuType[bodyPart], 0);  // inititate menu type
		   for (int i = 0; i < 3; i++)  //start from 1
			   changeJewelSlot(bodyPart, i, set.getLowRank(), 0, false);
		   calSetGUI();
	   }
	   else
	   {
		   // obtain list value
		   int[] list = mhagData.getArmorList(set.getLowRank(),
			   set.getBlade(), set.getFemale(), bodyPart);
		   int armorID = list[ind];
		   if(armorID == set.getArmorID()[bodyPart])return; //no change, no reset

		   // set armor id
		   set.setInUse(bodyPart, true);
		   set.setArmorID(bodyPart, armorID);

		   // get number of slots
		   Armor armor = mhagData.getArmor(bodyPart, armorID);
		   int nSlot = armor.getNumSlot();
		   //initialiate jewel menu lists
		   set.setNumJewel(bodyPart, nSlot);
		   Arrays.fill(jewelInd[bodyPart], 0);  // inititate jewelInd
		   for (int i = 0; i < nSlot; i++)  //start from 1
		   {
			   changeJewelSlot(bodyPart, i, set.getLowRank(), nSlot, true);
		   }
		   for (int i = nSlot; i < 3; i++)
		   {
			   changeJewelSlot(bodyPart, i, set.getLowRank(), 0, false);
		   }

		   if(nSlot == 0)calSetGUI();
	   }
    }

    private void jewelSlotAction(int bodyPart, int slotInd)
    {
	   if(adjust)return;  //don't perform action, when adjust combo box list;

	   JComboBox jewelSlot = getJewelSlotObj(bodyPart, slotInd);

	   int ind = jewelSlot.getSelectedIndex();
	   if(ind < 0) return; //initial menu

	   jewelInd[bodyPart][slotInd] = ind;

	   // change the other 2 comboBox

	   adjust = true;
	   int nSlot;
	   if(bodyPart < 5) // armor piece
	   {
		   Armor armor = mhagData.getArmor(bodyPart, set.getArmorID()[bodyPart]);
		   nSlot = armor.getNumSlot();  //armor slot
	   }
	   else if(bodyPart == 5) //weapon
	   {
		   nSlot = weaponMenu.getSelectedIndex();
	   }
	   else // charm
	   {
		   Charm charm = mhagData.getCharm(set.getCharmID());
		   nSlot = charm.getNumSlot();
	   }

	   //special case [2/1/0]
  	   boolean match = check200(bodyPart, nSlot);

//	   boolean match = false;
	   if(!match)
	   {
		   for (int i = 0; i < nSlot; i++)
		   {
			   if(i == slotInd)continue;
			   int nRest = nSlot - restSlots(bodyPart, i);

			   if(nRest <= 0)
			   {
				   changeJewelSlot(bodyPart, i, set.getLowRank(), 0, false);
			   }
			   else
			   {
				   changeJewelSlot(bodyPart, i, set.getLowRank(), nRest, true);
			   }

		   }
	    }
//	   getJewel(bodyPart);

	   setJewelGUI(bodyPart);
	   calSetGUI();
//	   System.out.printf(">> %s %s %s\n",jewelMenuType[bodyPart][0],jewelMenuType[bodyPart][1],jewelMenuType[bodyPart][2]);
//	   System.out.printf("> %s %s %s\n",jewelInd[bodyPart][0],jewelInd[bodyPart][1],jewelInd[bodyPart][2]);

	   adjust = false;

    }

    // get Jewel ID according to jewel buttton position
    private void getJewelID(int bodyPart)
    {
	    int[] jewelID = new int[3];
	    Arrays.fill(jewelID,-1);
	    for (int i = 0; i < 3; i++)
	    {
		    int ind = jewelInd[bodyPart][i];
		    if(ind <= 0)continue;
		    int[] list = mhagData.getJewelList(set.getLowRank(), jewelMenuType[bodyPart][i]);
		    jewelID[i] = list[ind];
	    }
    }

    // [2/0/0] slot menu case, only show 2/1
    private boolean check200(int bodyPart, int Slot)
    {
	    if(Slot != 3) return false;

	    boolean if2Slot = false;
	    int[] indLeft = new int[3];
	    Arrays.fill(indLeft, -1);
	    int ind2nd = -1;

	    int j = 0;
	    for (int i = 0; i < 3; i++)
	    {
		    int[] list = mhagData.getJewelList(set.getLowRank(), jewelMenuType[bodyPart][i]);
		    int ind = jewelInd[bodyPart][i];
		    if(ind <= 0)
		    {
			    indLeft[j++] = i;
			    continue;
		    }
		    int nSlot = mhagData.getJewel(list[ind]).getNumSlot();
		    if(nSlot == 2)
		    {
			    if2Slot = true;
			    ind2nd = i;
		    }
		    else
			    return false;
	    }
	    if(if2Slot )  // 2 & 0 & (0)
	    {
		    changeJewelSlot(bodyPart, ind2nd, set.getLowRank(), 3, true);
		    changeJewelSlot(bodyPart, indLeft[0], set.getLowRank(), 1, true);
		    changeJewelSlot(bodyPart, indLeft[1], set.getLowRank(), 0, false);
		    return true;
	    }
	    else
		    return false;
    }

    private int restSlots(int bodyPart, int slotInd)
    {
	    int num = 0;
	    for(int i = 0; i < 3; i++)
	    {
		    if(slotInd == i)continue;
		    int ind = jewelInd[bodyPart][i];
		    if(ind <= 0)continue;
		    int[] list = mhagData.getJewelList(set.getLowRank(), jewelMenuType[bodyPart][i]);
		    int jewelID = list[ind];
		    num += mhagData.getJewel(jewelID).getNumSlot();
	    }
	    return num;
    }

    private void setJewelGUI(int bodyPart)
    {

	   int nJewel = 0;
	   for(int i = 0; i < 3; i++)
	   {
		   int ind = jewelInd[bodyPart][i];
		   if(ind <=0 ) continue;
		   int[] list = mhagData.getJewelList(set.getLowRank(), jewelMenuType[bodyPart][i]);
		   set.setJewelID(bodyPart, nJewel, list[ind]);
		   nJewel++;
	   }
	   set.setNumJewel(bodyPart, nJewel);
    }


    private void initMhag() throws FileNotFoundException
    {
	mhag.setMethod(0);  // default method: calculator
	//mhag.setLogOpt(0);  // log in console screen
	mhag.setLogOpt(2);  // turn off log
	mhag.prepareLogFile();

	mhag.showMhagInfo(); //display MHAG welcome info
	mhagData.readFile(mhag); //read file
	mhagData.dataPreProc();  //pre process

	set.init();
	for (int i = 0; i < 7; i++)
	{
		Arrays.fill(jewelInd[i],0);   // init jewel IDs as null
		Arrays.fill(jewelMenuType[i],0);   // init jewel IDs as null
	}

    }

    /**
    * @param args the command line arguments
    */

    public JComboBox getArmorMenuObj(int bodyPart)
    {
	    JComboBox bodyMenu;
	    if(bodyPart == 0)
		    bodyMenu = headMenu;
	    else if(bodyPart == 1)
		    bodyMenu = chestMenu;
	    else if(bodyPart == 2)
		    bodyMenu = armsMenu;
	    else if(bodyPart == 3)
		    bodyMenu = waistMenu;
	    else
		    bodyMenu = legsMenu;

	    return bodyMenu;
    }

    public JComboBox getJewelSlotObj(int bodyPart, int slotInd)
    {
	    JComboBox jewelSlot;
	    if(bodyPart == 0)
	    {
		    if(slotInd == 0)
		    {
			    jewelSlot = headSlot1;
		    }
		    else if(slotInd == 1)
		    {
			    jewelSlot = headSlot2;
		    }
		    else
		    {
			    jewelSlot = headSlot3;
		    }
	    }
	    else if(bodyPart == 1)
	    {
		    if(slotInd == 0)
		    {
			    jewelSlot = chestSlot1;
		    }
		    else if(slotInd == 1)
		    {
			    jewelSlot = chestSlot2;
		    }
		    else
		    {
			    jewelSlot = chestSlot3;
		    }
	    }
	    else if(bodyPart == 2)
	    {
		    if(slotInd == 0)
		    {
			    jewelSlot = armSlot1;
		    }
		    else if(slotInd == 1)
		    {
			    jewelSlot = armSlot2;
		    }
		    else
		    {
			    jewelSlot = armSlot3;
		    }
	    }
	    else if(bodyPart == 3)
	    {
		    if(slotInd == 0)
		    {
			    jewelSlot = waistSlot1;
		    }
		    else if(slotInd == 1)
		    {
			    jewelSlot = waistSlot2;
		    }
		    else
		    {
			    jewelSlot = waistSlot3;
		    }
	    }
	    else if(bodyPart == 4)
	    {
		    if(slotInd == 0)
		    {
			    jewelSlot = legSlot1;
		    }
		    else if(slotInd == 1)
		    {
			    jewelSlot = legSlot2;
		    }
		    else
		    {
			    jewelSlot = legSlot3;
		    }
	    }
	    else if(bodyPart == 5)  //weapon
	    {
		    if(slotInd == 0)
		    {
			    jewelSlot = weaponSlot1;
		    }
		    else if(slotInd == 1)
		    {
			    jewelSlot = weaponSlot2;
		    }
		    else
		    {
			    jewelSlot = weaponSlot3;
		    }
	    }
	    else //charm slots
	    {
		    if(slotInd == 0)
		    {
			    jewelSlot = charmSlot1;
		    }
		    else if(slotInd == 1)
		    {
			    jewelSlot = charmSlot2;
		    }
		    else
		    {
			    jewelSlot = charmSlot3;
		    }
	    }
	    return jewelSlot;

    }

    public void changeArmorMenu(int bodyPart,boolean lowRank, boolean blade,
	    boolean female, boolean active)
    {
	    JComboBox bodyMenu = getArmorMenuObj(bodyPart);

	    if(!active)
	    {
		    bodyMenu.setVisible(false);
		    return;
	    }

	    int[] ind = mhagData.getArmorList(lowRank, blade, female, bodyPart);
	    int num = ind.length;
	    String[] name = mhagData.getArmorListMenu(bodyPart, female, num, ind);

	    bodyMenu.removeAllItems();
	    for(int i = 0; i < num; i++)
	    {
		    bodyMenu.addItem(name[i]);
	    }

	    bodyMenu.setVisible(true);

    }

    public void changeJewelSlot(int bodyPart, int slotInd,
	    boolean lowRank, int nSlot, boolean active)
    {
	    int[] jewelIndOld = new int[3];
	    for (int i = 0; i < 3; i++)  //walkaround,,removeAllItems() kills some jewelInd ata
		    jewelIndOld[i] = jewelInd[bodyPart][i];

	    JComboBox jewelSlot = getJewelSlotObj(bodyPart, slotInd);

	    if(!active)
	    {
		    jewelSlot.setVisible(false);
		    return;
	    }

	    int[] ind = mhagData.getJewelList(lowRank, nSlot);
	    int num = ind.length;

	    jewelSlot.removeAllItems();

	    jewelSlot.addItem("---"); //1st null item
	    for(int i = 1; i < num; i++)
	    {
 		    Jewel jewel = mhagData.getJewel(ind[i]);
		    jewelSlot.addItem(jewel.getJewelNameSkill());
	    }
	    jewelSlot.setVisible(true);

	    // keep the jewel ID if previously active
	    for (int i = 0; i < 3; i++) //walkaround
		    jewelInd[bodyPart][i] = jewelIndOld[i];

	    int[] indOld = mhagData.getJewelList(lowRank, jewelMenuType[bodyPart][slotInd]);

	    int id = indOld[jewelInd[bodyPart][slotInd]];
	    if(id != -1 )
	    {
		    for (int i = 1; i < num; i++)
		    {
			    if(ind[i] == id)
			    {
				    jewelSlot.setSelectedIndex(i);
				    jewelInd[bodyPart][slotInd] = i;
				    break;
			    }
		    }
	    }

	    jewelMenuType[bodyPart][slotInd] = nSlot;
    }

    public void changeCharmSkill(int skillNo,String skillClass, boolean active)
    {
	    JComboBox skillSlot;
	    JLabel skillLabel;
	    if(skillNo == 0)
	    {
		    skillSlot = charmSkill1;
		    skillLabel = skillPoint1;
	    }
	    else
	    {
		    skillSlot = charmSkill2;
		    skillLabel = skillPoint2;
	    }

	    if(!active)
	    {
		    skillSlot.setVisible(false);
		    skillLabel.setVisible(false);
		    return;
	    }

		int[] ind = mhagData.getSkillList(skillClass);
		int num = ind.length;

		skillSlot.removeAllItems();
		//skillSlot.addItem("---"); //No 1st null item
		for(int i = 0; i < num; i++)
		{
			Skill skill = mhagData.getSkill(ind[i]);
			skillSlot.addItem(skill.getSkillName());
		}

	    skillSlot.setVisible(true);
	    skillLabel.setVisible(true);
	    set.setCharmSkillID(skillNo,ind[0]);
    }

    public void changeCharmMenu(boolean lowRank)
    {

		int[] ind = mhagData.getCharmList(lowRank);
		int num = ind.length;

		charmMenu.removeAllItems();
		charmMenu.addItem("---"); //1st null item
		for(int i = 1; i < num; i++)
		{
			Charm charm = mhagData.getCharm(ind[i]);
			charmMenu.addItem(charm.getCharmName());
		}

	   charmMenu.setVisible(true);

    }

    public void initSetup(boolean lowRank, boolean blade, boolean female)
    {
	    for(int i = 0; i < 5; i++)
		    changeArmorMenu(i, lowRank, blade, female, true);

	    for(int i = 0; i < 7; i++)
	    {
		    for(int j = 0; j < 3; j++) // number 1-3
		    {
			changeJewelSlot(i, j, lowRank, 0, false);
		    }
	    }

	    weaponMenu.setSelectedIndex(0);  //reset Weapon menu

	    changeCharmMenu(lowRank);

	    for(int i = 0; i < 2; i++)
		    changeCharmSkill(i, "C", false);

    }

    public void changeGender(boolean lowRank, boolean blade, boolean female)
    {
	    adjust = true;
	    for(int i = 0; i < 5; i++)
	    {
		    JComboBox bodyMenu = getArmorMenuObj(i);

		    int entryOld = bodyMenu.getSelectedIndex();
		    int[] indOld = mhagData.getArmorList(lowRank, blade, !female, i);

		    int[] ind = mhagData.getArmorList(lowRank, blade, female, i);
		    int num = ind.length;
		    String[] name = mhagData.getArmorListMenu(i, female, num, ind);

		    bodyMenu.removeAllItems();
		    for(int j = 0; j < num; j++)
		    {
			    bodyMenu.addItem(name[j]);
			    if(ind[j] == indOld[entryOld])
			    {
				    bodyMenu.setSelectedIndex(j);
			    }
		    }
	    }
	    adjust = false;

    }

    public void calSetGUI()
    {
	   //boolean pass = set.checkSet(mhag, mhagData);  //check set
	   //if(!pass)
	   //{
	   //	   System.out.println("Error! Please Check!");
	   //      MhagUtil.logLine(mhag, "Error! Please Check!");
	   //}
	    String name = jTextSetName.getText();
	    set.setSetName(name);

	   set.calcSet(mhag, mhagData);   //calculate set

	   stream.reset();
  	   set.save(mhag, mhagData, stream);  // save results
	   stream.rewind();
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                MhagGui mhagGui = new MhagGui();

		try {
			mhagGui.initMhag();  // initialize mhag
		} catch (FileNotFoundException ex) {
			Logger.getLogger(MhagGui.class.getName()).log(Level.SEVERE, null, ex);
		}

		mhagGui.stream = new TextAreaPrintStream(mhagGui.jTextPreview, System.out);

		mhagGui.setVisible(true);

		mhagGui.initSetup(false, true, false); // by default

            }
        });
    }

    	// GUI static MHAG
    	private Mhag mhag = new Mhag();
    	private Set set = new Set();
    	private MhagData mhagData = new MhagData();
	private TextAreaPrintStream stream;
	private int[][] jewelInd = new int[7][3]; //jewel index in each jewel button list
	private int[][] jewelMenuType = new int[7][3]; //menu type in each jewel button position
	private boolean adjust = false; // adjust menu, don't perform calculation
	int saveOpt =0;  //save option for GUI

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel about;
        private javax.swing.JComboBox armSlot1;
        private javax.swing.JComboBox armSlot2;
        private javax.swing.JComboBox armSlot3;
        private javax.swing.JLabel armsLabel;
        private javax.swing.JComboBox armsMenu;
        private javax.swing.JPanel batch;
        private javax.swing.JRadioButton blade;
        private javax.swing.JPanel calculator;
        private javax.swing.JLabel charmLabel;
        private javax.swing.JComboBox charmMenu;
        private javax.swing.JComboBox charmSkill1;
        private javax.swing.JComboBox charmSkill2;
        private javax.swing.JLabel charmSkillLabel;
        private javax.swing.JComboBox charmSlot1;
        private javax.swing.JComboBox charmSlot2;
        private javax.swing.JComboBox charmSlot3;
        private javax.swing.JLabel chestLabel;
        private javax.swing.JComboBox chestMenu;
        private javax.swing.JComboBox chestSlot1;
        private javax.swing.JComboBox chestSlot2;
        private javax.swing.JComboBox chestSlot3;
        private javax.swing.JRadioButton code;
        private javax.swing.JRadioButton female;
        private javax.swing.JPanel generator;
        private javax.swing.JRadioButton gunner;
        private javax.swing.JLabel headLabel;
        private javax.swing.JComboBox headMenu;
        private javax.swing.JComboBox headSlot1;
        private javax.swing.JComboBox headSlot2;
        private javax.swing.JComboBox headSlot3;
        private javax.swing.JRadioButton highRank;
        private javax.swing.JRadioButton html;
        private javax.swing.JPanel hunterType;
        private javax.swing.ButtonGroup hunterTypeGroup;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JScrollPane jScrollPreview;
        private javax.swing.JTabbedPane jTabbedPane1;
        private javax.swing.JTextField jTextData;
        private javax.swing.JTextArea jTextPreview;
        private javax.swing.JTextField jTextSetName;
        private javax.swing.JComboBox legSlot1;
        private javax.swing.JComboBox legSlot2;
        private javax.swing.JComboBox legSlot3;
        private javax.swing.JLabel legsLabel;
        private javax.swing.JComboBox legsMenu;
        private javax.swing.JRadioButton lowRank;
        private javax.swing.JRadioButton male;
        private javax.swing.JPanel output;
        private javax.swing.ButtonGroup outputGroup;
        private javax.swing.JPanel rank;
        private javax.swing.ButtonGroup rankGroup;
        private javax.swing.JButton saveOutput;
        private javax.swing.JPanel setNamePanel;
        private javax.swing.JPanel setup;
        private javax.swing.JPanel sex;
        private javax.swing.ButtonGroup sexGroup;
        private javax.swing.JLabel skillPoint1;
        private javax.swing.JLabel skillPoint2;
        private javax.swing.JRadioButton text;
        private javax.swing.JLabel waistLabel;
        private javax.swing.JComboBox waistMenu;
        private javax.swing.JComboBox waistSlot1;
        private javax.swing.JComboBox waistSlot2;
        private javax.swing.JComboBox waistSlot3;
        private javax.swing.JLabel weaponLabel;
        private javax.swing.JComboBox weaponMenu;
        private javax.swing.JComboBox weaponSlot1;
        private javax.swing.JComboBox weaponSlot2;
        private javax.swing.JComboBox weaponSlot3;
        // End of variables declaration//GEN-END:variables

}
