
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MhagGui.java
 *
 * Created on Dec 27, 2010, 4:02:42 AM
 */

/**
 *
 * @author lvmy
 */
public class MhagGui extends javax.swing.JFrame {

    /** Creates new form MhagGui */
    public MhagGui() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                rankGroup = new javax.swing.ButtonGroup();
                hunterTypeGroup = new javax.swing.ButtonGroup();
                sexGroup = new javax.swing.ButtonGroup();
                outputGroup = new javax.swing.ButtonGroup();
                jTabbedPane1 = new javax.swing.JTabbedPane();
                calculator = new javax.swing.JPanel();
                rank = new javax.swing.JPanel();
                lowRank = new javax.swing.JRadioButton();
                highRank = new javax.swing.JRadioButton();
                hunterType = new javax.swing.JPanel();
                blade = new javax.swing.JRadioButton();
                gunner = new javax.swing.JRadioButton();
                sex = new javax.swing.JPanel();
                male = new javax.swing.JRadioButton();
                female = new javax.swing.JRadioButton();
                setup = new javax.swing.JPanel();
                weaponMenu = new javax.swing.JComboBox();
                headMenu = new javax.swing.JComboBox();
                chestMenu = new javax.swing.JComboBox();
                armsMenu = new javax.swing.JComboBox();
                waistMenu = new javax.swing.JComboBox();
                legsMenu = new javax.swing.JComboBox();
                charmMenu = new javax.swing.JComboBox();
                weapon = new javax.swing.JLabel();
                head = new javax.swing.JLabel();
                chest = new javax.swing.JLabel();
                arms = new javax.swing.JLabel();
                waist = new javax.swing.JLabel();
                legs = new javax.swing.JLabel();
                charm = new javax.swing.JLabel();
                charmSkill = new javax.swing.JLabel();
                weaponSlot1 = new javax.swing.JComboBox();
                weaponSlot2 = new javax.swing.JComboBox();
                weaponSlot3 = new javax.swing.JComboBox();
                headSlot1 = new javax.swing.JComboBox();
                headSlot2 = new javax.swing.JComboBox();
                headSlot3 = new javax.swing.JComboBox();
                chestSlot1 = new javax.swing.JComboBox();
                chestSlot2 = new javax.swing.JComboBox();
                chestSlot3 = new javax.swing.JComboBox();
                armSlot1 = new javax.swing.JComboBox();
                armSlot2 = new javax.swing.JComboBox();
                armSlot3 = new javax.swing.JComboBox();
                waistSlot1 = new javax.swing.JComboBox();
                waistSlot2 = new javax.swing.JComboBox();
                waistSlot3 = new javax.swing.JComboBox();
                legSlot1 = new javax.swing.JComboBox();
                legSlot2 = new javax.swing.JComboBox();
                legSlot3 = new javax.swing.JComboBox();
                charmSlot1 = new javax.swing.JComboBox();
                charmSlot2 = new javax.swing.JComboBox();
                charmSlot3 = new javax.swing.JComboBox();
                charmSkill1 = new javax.swing.JComboBox();
                charmSkill2 = new javax.swing.JComboBox();
                jewelLabel = new javax.swing.JLabel();
                jewelLabel1 = new javax.swing.JLabel();
                jewelLabel2 = new javax.swing.JLabel();
                skillPoint1 = new javax.swing.JLabel();
                skillPoint2 = new javax.swing.JLabel();
                output = new javax.swing.JPanel();
                text = new javax.swing.JRadioButton();
                html = new javax.swing.JRadioButton();
                code = new javax.swing.JRadioButton();
                saveOutput = new javax.swing.JButton();
                jScrollPreview = new javax.swing.JScrollPane();
                jTextPreview = new javax.swing.JTextPane();
                batch = new javax.swing.JPanel();
                generator = new javax.swing.JPanel();
                about = new javax.swing.JPanel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setResizable(false);

                rank.setBorder(javax.swing.BorderFactory.createTitledBorder("Rank"));

                rankGroup.add(lowRank);
                lowRank.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                lowRank.setText("Low Rank");

                rankGroup.add(highRank);
                highRank.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                highRank.setSelected(true);
                highRank.setText("High Rank");

                javax.swing.GroupLayout rankLayout = new javax.swing.GroupLayout(rank);
                rank.setLayout(rankLayout);
                rankLayout.setHorizontalGroup(
                        rankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(rankLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(rankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lowRank)
                                        .addComponent(highRank))
                                .addContainerGap(14, Short.MAX_VALUE))
                );
                rankLayout.setVerticalGroup(
                        rankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(rankLayout.createSequentialGroup()
                                .addComponent(lowRank)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(highRank)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                hunterType.setBorder(javax.swing.BorderFactory.createTitledBorder("Hunter Type"));

                hunterTypeGroup.add(blade);
                blade.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                blade.setSelected(true);
                blade.setText("Blademaster");
                blade.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bladeActionPerformed(evt);
                        }
                });

                hunterTypeGroup.add(gunner);
                gunner.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                gunner.setText("Gunner");

                javax.swing.GroupLayout hunterTypeLayout = new javax.swing.GroupLayout(hunterType);
                hunterType.setLayout(hunterTypeLayout);
                hunterTypeLayout.setHorizontalGroup(
                        hunterTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(hunterTypeLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(hunterTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(blade)
                                        .addComponent(gunner))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                hunterTypeLayout.setVerticalGroup(
                        hunterTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(hunterTypeLayout.createSequentialGroup()
                                .addComponent(blade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gunner)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                sex.setBorder(javax.swing.BorderFactory.createTitledBorder("Gender"));

                sexGroup.add(male);
                male.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                male.setSelected(true);
                male.setText("Male");

                sexGroup.add(female);
                female.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                female.setText("Female");

                javax.swing.GroupLayout sexLayout = new javax.swing.GroupLayout(sex);
                sex.setLayout(sexLayout);
                sexLayout.setHorizontalGroup(
                        sexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sexLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(sexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(male)
                                        .addComponent(female))
                                .addContainerGap(17, Short.MAX_VALUE))
                );
                sexLayout.setVerticalGroup(
                        sexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sexLayout.createSequentialGroup()
                                .addComponent(male)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(female)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                setup.setBorder(javax.swing.BorderFactory.createTitledBorder("Setup"));

                weaponMenu.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                weaponMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Slot", "1 Slot", "2 Slots", "3 Slots" }));

                headMenu.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                headMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                chestMenu.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                chestMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                armsMenu.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                armsMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                waistMenu.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                waistMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                legsMenu.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                legsMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                charmMenu.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                charmMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                weapon.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                weapon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/weapon.png"))); // NOI18N
                weapon.setLabelFor(weaponMenu);
                weapon.setToolTipText("Weapon");

                head.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                head.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/head.png"))); // NOI18N
                head.setLabelFor(headMenu);
                head.setToolTipText("Head");

                chest.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                chest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/chest.png"))); // NOI18N
                chest.setLabelFor(chestMenu);
                chest.setToolTipText("Chest");

                arms.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                arms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/arms.png"))); // NOI18N
                arms.setLabelFor(armsMenu);
                arms.setToolTipText("Arms");

                waist.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                waist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/waist.png"))); // NOI18N
                waist.setLabelFor(waistMenu);
                waist.setToolTipText("Waist");

                legs.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                legs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/legs.png"))); // NOI18N
                legs.setLabelFor(legsMenu);
                legs.setToolTipText("Legs");

                charm.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                charm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/charm.png"))); // NOI18N
                charm.setLabelFor(charmMenu);
                charm.setToolTipText("Charm");

                charmSkill.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                charmSkill.setLabelFor(charmSkill1);
                charmSkill.setText("Charm Skill");

                weaponSlot1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                weaponSlot1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                weaponSlot2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                weaponSlot2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                weaponSlot3.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                weaponSlot3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                headSlot1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                headSlot1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                headSlot2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                headSlot2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                headSlot3.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                headSlot3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                chestSlot1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                chestSlot1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                chestSlot2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                chestSlot2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                chestSlot3.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                chestSlot3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                armSlot1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                armSlot1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                armSlot2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                armSlot2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                armSlot3.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                armSlot3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                waistSlot1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                waistSlot1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                waistSlot2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                waistSlot2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                waistSlot3.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                waistSlot3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                legSlot1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                legSlot1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                legSlot2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                legSlot2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                legSlot3.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                legSlot3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                charmSlot1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                charmSlot1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                charmSlot2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                charmSlot2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                charmSlot3.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                charmSlot3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                charmSkill1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                charmSkill1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                charmSkill2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                charmSkill2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));

                jewelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/jewel.png"))); // NOI18N
                jewelLabel.setToolTipText("Jewels");

                jewelLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/jewel.png"))); // NOI18N
                jewelLabel1.setToolTipText("Jewels");

                jewelLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/jewel.png"))); // NOI18N
                jewelLabel2.setToolTipText("Jewels");

                skillPoint1.setLabelFor(charmSkill1);
                skillPoint1.setText("+10");

                skillPoint2.setLabelFor(charmSkill2);
                skillPoint2.setText("-10");

                javax.swing.GroupLayout setupLayout = new javax.swing.GroupLayout(setup);
                setup.setLayout(setupLayout);
                setupLayout.setHorizontalGroup(
                        setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(setupLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(setupLayout.createSequentialGroup()
                                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(head, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                                        .addComponent(weapon, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                                        .addComponent(chest, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                                        .addComponent(arms, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                                        .addComponent(waist, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                                        .addComponent(legs)
                                                        .addComponent(charm))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(setupLayout.createSequentialGroup()
                                                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(waistMenu, 0, 160, Short.MAX_VALUE)
                                                                        .addComponent(weaponMenu, 0, 160, Short.MAX_VALUE)
                                                                        .addComponent(headMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(chestMenu, javax.swing.GroupLayout.Alignment.TRAILING, 0, 160, Short.MAX_VALUE)
                                                                        .addComponent(armsMenu, javax.swing.GroupLayout.Alignment.TRAILING, 0, 160, Short.MAX_VALUE)
                                                                        .addComponent(charmMenu, javax.swing.GroupLayout.Alignment.TRAILING, 0, 160, Short.MAX_VALUE)
                                                                        .addComponent(legsMenu, javax.swing.GroupLayout.Alignment.TRAILING, 0, 160, Short.MAX_VALUE))
                                                                .addGap(3, 3, 3))
                                                        .addComponent(charmSkill))
                                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(charmSkill1, 0, 100, Short.MAX_VALUE)
                                                        .addComponent(charmSlot1, 0, 100, Short.MAX_VALUE)
                                                        .addComponent(legSlot1, 0, 100, Short.MAX_VALUE)
                                                        .addComponent(waistSlot1, 0, 100, Short.MAX_VALUE)
                                                        .addComponent(armSlot1, 0, 100, Short.MAX_VALUE)
                                                        .addComponent(chestSlot1, 0, 100, Short.MAX_VALUE)
                                                        .addComponent(headSlot1, 0, 100, Short.MAX_VALUE)
                                                        .addComponent(weaponSlot1, 0, 100, Short.MAX_VALUE))
                                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(setupLayout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(weaponSlot2, 0, 100, Short.MAX_VALUE)
                                                                        .addComponent(chestSlot2, 0, 100, Short.MAX_VALUE)
                                                                        .addComponent(armSlot2, 0, 100, Short.MAX_VALUE)
                                                                        .addComponent(waistSlot2, 0, 100, Short.MAX_VALUE)
                                                                        .addComponent(legSlot2, 0, 100, Short.MAX_VALUE)
                                                                        .addComponent(charmSlot2, 0, 100, Short.MAX_VALUE)
                                                                        .addComponent(headSlot2, 0, 100, Short.MAX_VALUE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(charmSlot3, 0, 100, Short.MAX_VALUE)
                                                                        .addComponent(legSlot3, 0, 100, Short.MAX_VALUE)
                                                                        .addComponent(waistSlot3, 0, 100, Short.MAX_VALUE)
                                                                        .addComponent(armSlot3, 0, 100, Short.MAX_VALUE)
                                                                        .addComponent(chestSlot3, 0, 100, Short.MAX_VALUE)
                                                                        .addComponent(headSlot3, 0, 100, Short.MAX_VALUE)
                                                                        .addComponent(weaponSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(setupLayout.createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addComponent(skillPoint1)
                                                                .addGap(20, 20, 20)
                                                                .addComponent(charmSkill2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(skillPoint2)))
                                                .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setupLayout.createSequentialGroup()
                                                .addComponent(jewelLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(82, 82, 82)
                                                .addComponent(jewelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(84, 84, 84)
                                                .addComponent(jewelLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(59, 59, 59))))
                );
                setupLayout.setVerticalGroup(
                        setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setupLayout.createSequentialGroup()
                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jewelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jewelLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jewelLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(setupLayout.createSequentialGroup()
                                                .addComponent(weaponSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(headSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(chestSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(armSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(waistSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(legSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(charmSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(charmSkill1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(charmSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(charmSkill2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(skillPoint1)
                                                        .addComponent(skillPoint2)))
                                        .addGroup(setupLayout.createSequentialGroup()
                                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(weapon)
                                                        .addComponent(weaponMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(head)
                                                        .addComponent(headMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(chest)
                                                        .addComponent(chestMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(armsMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(arms))
                                                .addGap(18, 18, 18)
                                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(waistMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(waist))
                                                .addGap(18, 18, 18)
                                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(legsMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(legs))
                                                .addGap(18, 18, 18)
                                                .addGroup(setupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(charm)
                                                        .addComponent(charmMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(setupLayout.createSequentialGroup()
                                                .addComponent(weaponSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(headSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(chestSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(armSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(waistSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(legSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(charmSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(setupLayout.createSequentialGroup()
                                                .addComponent(weaponSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(headSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(chestSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(armSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(waistSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(legSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(charmSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                );

                output.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));

                outputGroup.add(text);
                text.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                text.setSelected(true);
                text.setText("TEXT");

                outputGroup.add(html);
                html.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                html.setText("HTML");
                html.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                htmlActionPerformed(evt);
                        }
                });

                outputGroup.add(code);
                code.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12));
                code.setText("Code");

                saveOutput.setFont(new java.awt.Font("Monospaced", 0, 12));
                saveOutput.setText("Save");

                javax.swing.GroupLayout outputLayout = new javax.swing.GroupLayout(output);
                output.setLayout(outputLayout);
                outputLayout.setHorizontalGroup(
                        outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(outputLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(outputLayout.createSequentialGroup()
                                                .addComponent(text)
                                                .addGap(18, 18, 18)
                                                .addComponent(html))
                                        .addGroup(outputLayout.createSequentialGroup()
                                                .addComponent(code)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(saveOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                outputLayout.setVerticalGroup(
                        outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outputLayout.createSequentialGroup()
                                .addGroup(outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(text)
                                        .addComponent(html))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(code)
                                        .addComponent(saveOutput))
                                .addContainerGap())
                );

                jScrollPreview.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
                jScrollPreview.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

                jTextPreview.setBorder(javax.swing.BorderFactory.createTitledBorder("Preview"));
                jTextPreview.setEditable(false);
                jTextPreview.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
                jTextPreview.setText("================================================================================\nMedic's Set                             High Rank   Blademaster \n--------------------------------------------------------------------------------\nWeapon                                  OO-   Steadfast+ Recovery \nGrace Earring                           ---     \nGobul Mail+                             O--   Steadfast+  \nGobul Vambraces+                        O--   Medicine  \nGobul Faulds+                           O--   Medicine  \nGobul Greaves+                          OOO   Voracious  \nRec Level +7                            OO-   Panacea  \n--------------------------------------------------------------------------------\n                    WEP HEA CHE ARM WAI LEG CHA TOT\nMax Defense         ---  10  74  74  74  74 --- 306 \nResist: Fire        ---   0  -2  -2  -2  -2 ---  -8 \n        Water       ---   0   4   4   4   4 ---  16 \n        Ice         ---   0   0   0   0   0 ---   0 \n        Thunder     ---   0  -4  -4  -4  -4 --- -16 \n        Dragon      ---   0   2   2   2   2 ---   8 \n--------------------------------------------------------------------------------\nSKills: Wide-Range  ---  20 --- --- --- --- ---  20 → Wide-Range +2\n        Stun          2 ---   4   4   4   2 ---  16 → Negate Stun\n        Eating       -1 ---   2   4   5   5 ---  15 → Speed Eating +2\n        Rec Level   --- --- ---   1   1  -2  10  10 → Recovery Up\n        Expert      --- ---   3   2   1   2 ---   8   ---\n        Rec Speed     1 ---  -2  -2  -2  -2  -1  -8   ---\n================================================================================");
                jTextPreview.setOpaque(false);
                jScrollPreview.setViewportView(jTextPreview);

                javax.swing.GroupLayout calculatorLayout = new javax.swing.GroupLayout(calculator);
                calculator.setLayout(calculatorLayout);
                calculatorLayout.setHorizontalGroup(
                        calculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(calculatorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(calculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(calculatorLayout.createSequentialGroup()
                                                .addComponent(rank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(hunterType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(setup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                calculatorLayout.setVerticalGroup(
                        calculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calculatorLayout.createSequentialGroup()
                                .addGroup(calculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, calculatorLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPreview))
                                        .addGroup(calculatorLayout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addGroup(calculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(output, 0, 89, Short.MAX_VALUE)
                                                        .addComponent(hunterType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(rank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(sex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(setup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(64, 64, 64))
                );

                jTabbedPane1.addTab("Calculator", calculator);

                javax.swing.GroupLayout batchLayout = new javax.swing.GroupLayout(batch);
                batch.setLayout(batchLayout);
                batchLayout.setHorizontalGroup(
                        batchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1177, Short.MAX_VALUE)
                );
                batchLayout.setVerticalGroup(
                        batchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 522, Short.MAX_VALUE)
                );

                jTabbedPane1.addTab("Batch", batch);

                javax.swing.GroupLayout generatorLayout = new javax.swing.GroupLayout(generator);
                generator.setLayout(generatorLayout);
                generatorLayout.setHorizontalGroup(
                        generatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1177, Short.MAX_VALUE)
                );
                generatorLayout.setVerticalGroup(
                        generatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 522, Short.MAX_VALUE)
                );

                jTabbedPane1.addTab("Generator", generator);

                javax.swing.GroupLayout aboutLayout = new javax.swing.GroupLayout(about);
                about.setLayout(aboutLayout);
                aboutLayout.setHorizontalGroup(
                        aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1177, Short.MAX_VALUE)
                );
                aboutLayout.setVerticalGroup(
                        aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 522, Short.MAX_VALUE)
                );

                jTabbedPane1.addTab("About", about);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1189, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void bladeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bladeActionPerformed
	    // TODO add your handling code here:
    }//GEN-LAST:event_bladeActionPerformed

    private void htmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htmlActionPerformed
	    // TODO add your handling code here:
    }//GEN-LAST:event_htmlActionPerformed

    private static void initMhag(Mhag mhag, MhagData mhagData) throws FileNotFoundException
    {
	mhag.setMethod(0);  // default method: calculator
	mhag.setLogOpt(0);  // log in console screen
	//mhag.setLogOpt(2);  // turn off log
	mhag.prepareLogFile();

	mhag.showMhagInfo(); //display MHAG welcome info
	mhagData.readFile(mhag); //read file
	mhagData.dataPreProc();  //pre process
    }

    /**
    * @param args the command line arguments
    */
    public void changeHeadMenu(MhagData mhagData, boolean lowRank,
	    boolean blade, boolean female)
    {

		int[] ind = mhagData.getArmorList(true, true, false, 1);
		int num = ind.length;
		String[] name = mhagData.getArmorListMenu(1, false, num, ind);

		headMenu.removeAllItems();
		for(int i = 0; i < num; i++)
		{
			headMenu.addItem(name[i]);
		}


    }

    public void changeHeadSlot1(MhagData mhagData, boolean lowRank, int nSlot)
    {

		int[] ind = mhagData.getJewelList(true, nSlot);
		int num = ind.length;

		headSlot1.removeAllItems();
		headSlot1.addItem("---"); //1st null item
		for(int i = 1; i < num; i++)
		{
			Jewel jewel = mhagData.getJewel(ind[i]);
			headSlot1.addItem(jewel.getJewelNameShort());
		}
		headSlot1.enable();
		headSlot3.disable();

    }

    public void changeCharmSkill1(MhagData mhagData, String skillClass)
    {

		int[] ind = mhagData.getSkillList(skillClass);
		int num = ind.length;

		charmSkill1.removeAllItems();
		charmSkill1.addItem("---"); //1st null item
		for(int i = 1; i < num; i++)
		{
			Skill skill = mhagData.getSkill(ind[i]);
			charmSkill1.addItem(skill.getSkillName());
		}
		charmSkill1.enable();
		charmSkill2.disable();

    }

    public void changeCharm(MhagData mhagData, boolean lowRank)
    {

		int[] ind = mhagData.getCharmList(lowRank);
		int num = ind.length;

		charmMenu.removeAllItems();
		charmMenu.addItem("---"); //1st null item
		for(int i = 1; i < num; i++)
		{
			Charm charm = mhagData.getCharm(ind[i]);
			charmMenu.addItem(charm.getCharmName());
		}
		charmMenu.enable();

    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

		// initialize Mhag
		Mhag mhag = new Mhag();
		MhagData mhagData = new MhagData();

		try {
			initMhag(mhag, mhagData);  // initialize mhag
		} catch (FileNotFoundException ex) {
			Logger.getLogger(MhagGui.class.getName()).log(Level.SEVERE, null, ex);
		}

                MhagGui mhagGui = new MhagGui();
		mhagGui.setVisible(true);

		mhagGui.changeHeadMenu(mhagData, true, true, false);

		mhagGui.changeHeadSlot1(mhagData, true, 1);

		mhagGui.changeCharmSkill1(mhagData, "A");

		mhagGui.changeCharm(mhagData, false);

            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel about;
        private javax.swing.JComboBox armSlot1;
        private javax.swing.JComboBox armSlot2;
        private javax.swing.JComboBox armSlot3;
        private javax.swing.JLabel arms;
        private javax.swing.JComboBox armsMenu;
        private javax.swing.JPanel batch;
        private javax.swing.JRadioButton blade;
        private javax.swing.JPanel calculator;
        private javax.swing.JLabel charm;
        private javax.swing.JComboBox charmMenu;
        private javax.swing.JLabel charmSkill;
        private javax.swing.JComboBox charmSkill1;
        private javax.swing.JComboBox charmSkill2;
        private javax.swing.JComboBox charmSlot1;
        private javax.swing.JComboBox charmSlot2;
        private javax.swing.JComboBox charmSlot3;
        private javax.swing.JLabel chest;
        private javax.swing.JComboBox chestMenu;
        private javax.swing.JComboBox chestSlot1;
        private javax.swing.JComboBox chestSlot2;
        private javax.swing.JComboBox chestSlot3;
        private javax.swing.JRadioButton code;
        private javax.swing.JRadioButton female;
        private javax.swing.JPanel generator;
        private javax.swing.JRadioButton gunner;
        private javax.swing.JLabel head;
        private javax.swing.JComboBox headMenu;
        private javax.swing.JComboBox headSlot1;
        private javax.swing.JComboBox headSlot2;
        private javax.swing.JComboBox headSlot3;
        private javax.swing.JRadioButton highRank;
        private javax.swing.JRadioButton html;
        private javax.swing.JPanel hunterType;
        private javax.swing.ButtonGroup hunterTypeGroup;
        private javax.swing.JScrollPane jScrollPreview;
        private javax.swing.JTabbedPane jTabbedPane1;
        private javax.swing.JTextPane jTextPreview;
        private javax.swing.JLabel jewelLabel;
        private javax.swing.JLabel jewelLabel1;
        private javax.swing.JLabel jewelLabel2;
        private javax.swing.JComboBox legSlot1;
        private javax.swing.JComboBox legSlot2;
        private javax.swing.JComboBox legSlot3;
        private javax.swing.JLabel legs;
        private javax.swing.JComboBox legsMenu;
        private javax.swing.JRadioButton lowRank;
        private javax.swing.JRadioButton male;
        private javax.swing.JPanel output;
        private javax.swing.ButtonGroup outputGroup;
        private javax.swing.JPanel rank;
        private javax.swing.ButtonGroup rankGroup;
        private javax.swing.JButton saveOutput;
        private javax.swing.JPanel setup;
        private javax.swing.JPanel sex;
        private javax.swing.ButtonGroup sexGroup;
        private javax.swing.JLabel skillPoint1;
        private javax.swing.JLabel skillPoint2;
        private javax.swing.JRadioButton text;
        private javax.swing.JLabel waist;
        private javax.swing.JComboBox waistMenu;
        private javax.swing.JComboBox waistSlot1;
        private javax.swing.JComboBox waistSlot2;
        private javax.swing.JComboBox waistSlot3;
        private javax.swing.JLabel weapon;
        private javax.swing.JComboBox weaponMenu;
        private javax.swing.JComboBox weaponSlot1;
        private javax.swing.JComboBox weaponSlot2;
        private javax.swing.JComboBox weaponSlot3;
        // End of variables declaration//GEN-END:variables

}
